# Generated by Django 4.1.7 on 2023-03-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('location', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('county', models.CharField(max_length=155)),
                ('address', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=155, null=True)),
                ('county', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('orphaned', 'orphaned'), ('street', 'street'), ('special', 'special')], default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='home_media'),
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('anonymous', 'anonymous'), ('dedicated', 'dedicated')], max_length=155)),
                ('message', models.TextField()),
                ('donation_amount', models.CharField(max_length=155)),
                ('donation_date', models.DateField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.donor')),
                ('home', models.ManyToManyField(to='categories.childrenhome')),
            ],
        ),
        migrations.AddField(
            model_name='childrenhome',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
