# Generated by Django 4.1.7 on 2023-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_childrenhome_donor_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Orphaned', 'Orphaned'), ('Street', 'Street'), ('Special', 'Special')], max_length=55),
        ),
        migrations.CreateModel(
            name='ChildrenHomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='children_home_images/')),
                ('num_children', models.PositiveIntegerField()),
                ('age_group', models.CharField(max_length=255)),
                ('main_challenges', models.TextField()),
                ('activities', models.TextField()),
                ('ChildrenHome_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
