# Generated by Django 4.1.7 on 2023-03-17 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_type_childrenhomedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrenhomedetails',
            name='ChildrenHome_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.childrenhome'),
        ),
    ]
