# Generated by Django 4.1.7 on 2023-03-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_childrenhomedetails_childrenhome_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childrenhomedetails',
            old_name='ChildrenHome_id',
            new_name='ChildrenHome',
        ),
    ]
