# Generated by Django 4.1.7 on 2023-03-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_rename_childrenhome_id_childrenhomedetails_childrenhome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childrenhomedetails',
            name='ChildrenHome',
        ),
        migrations.AlterField(
            model_name='childrenhomedetails',
            name='image',
            field=models.ImageField(upload_to='categories_media'),
        ),
    ]
