# Generated by Django 4.1.7 on 2023-04-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_remove_childrenhome_image_childrenhome_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrenhome',
            name='about_us',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
