# Generated by Django 4.1.7 on 2023-04-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_childrenhome_management_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='avatar',
            field=models.ImageField(default=1, upload_to='donor_image'),
            preserve_default=False,
        ),
    ]
